---
title: Bachelor Thesis
author:
  - name: Maximilian Elixhauser
    corresponding: true
    email: maximilian.elixhauser@stud.plus.ac.at
    roles:
      - Author
    affiliations:
      - University of Salzburg
keywords:
  - Data

abstract: |
  ...
plain-language-summary: |
  ...
key-points:
  - ...
  - ...
  - ...
date: last-modified
bibliography: thesis_ref.bib
number-sections: true
jupyter: python3
format:
  pdf:
    documentclass: scrreprt
  html:
    toc: true
    toc-depth: 3
---

## Acknowledgments

Based on TOS:

“This thesis includes results derived from the ATM Datasets made available by EUROCONTROL (©2025). EUROCONTROL does not necessarily endorse or support the conclusions drawn herein and shall not be liable for any direct or indirect damages arising out of or in connection with this work.”

And for Figures for example: "Figure 1. Sankey diagram of daily passenger flows (April 2020) among selected European airports. Source: @eurocontrolData2025."



## Introduction

### Context & Motivation

### Research questions & Objectives

### Thesis Outline

## Literature Review

### Network Epidemiology & SIR Models

### COVID-19 & Global Mobility Networks (GMN)

### Data Challenges in Flight-Based Epidemiology

## Methodology

### Data Sources & Feasibility

### Model Implementation

### Simulation Steps & Parameter CHoices

### Statistical / Correlation Analysis

## Results & Analysis

### Simulation Outcomes

### Comparison to Real Data

### Excess Mortality Correlation

## Discussion

### Did Early Arrival Matter?

### Model Reliability & Data Biases

### Limitations & Future Work

## Conclusion

### Major Takeaways

### Practical Implications

### Final Thoughts

## References

::: {#refs}
:::